// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEThkqjr59H2tiYiU4Yb1YjflLUi2RAI0',
    appId: '1:234385700116:web:03bf028a125b1dab903e01',
    messagingSenderId: '234385700116',
    projectId: 'meal-go-7b533',
    authDomain: 'meal-go-7b533.firebaseapp.com',
    storageBucket: 'meal-go-7b533.firebasestorage.app',
    measurementId: 'G-YYPKGMRZF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWuda8L-2xPnrAVYK9AQwPY1M1i7uewK8',
    appId: '1:234385700116:android:5975c027dcc66edd903e01',
    messagingSenderId: '234385700116',
    projectId: 'meal-go-7b533',
    storageBucket: 'meal-go-7b533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESn-pYFNVvci-JD1dxpDCrADnD9sNXsI',
    appId: '1:234385700116:ios:79d0f3b453c2bb45903e01',
    messagingSenderId: '234385700116',
    projectId: 'meal-go-7b533',
    storageBucket: 'meal-go-7b533.firebasestorage.app',
    iosBundleId: 'com.example.mealGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAESn-pYFNVvci-JD1dxpDCrADnD9sNXsI',
    appId: '1:234385700116:ios:79d0f3b453c2bb45903e01',
    messagingSenderId: '234385700116',
    projectId: 'meal-go-7b533',
    storageBucket: 'meal-go-7b533.firebasestorage.app',
    iosBundleId: 'com.example.mealGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEThkqjr59H2tiYiU4Yb1YjflLUi2RAI0',
    appId: '1:234385700116:web:6fbbfcf0c954ddec903e01',
    messagingSenderId: '234385700116',
    projectId: 'meal-go-7b533',
    authDomain: 'meal-go-7b533.firebaseapp.com',
    storageBucket: 'meal-go-7b533.firebasestorage.app',
    measurementId: 'G-5QVYJ97ZP6',
  );
}
